### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Sukshith27**

### CODE REVIEW

**Comment by kiranjd** [comment]
@Sukshith27 There's a merge conflict

**Comment by kiranjd** [comment]
Run these run after the other:

1. git remote add upstream https://github.com/kiranjd/rn-animation.git
2. git fetch
3. git checkout upstream master
4. git pull
5. git checkout develop
6. git pull upstream master

**Comment by kiranjd** [comment]
After the above you should see a the conflict. Resolve that conflict and push the changes to develop branch

**Comment by Sukshith27** [comment]
merge

**Pull request merged**
